---
Name: silverstripebasesiteconfig
---
SilverStripe\Admin\LeftAndMain:
  application_name: 'Dynamic'
  application_link: 'http://www.dynamicagency.com'
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Dynamic\CoreTools\ORM\CoreToolsPageFieldsDataExtension
Dynamic\Base\Page\HomePage:
  extensions:
    - DNADesign\Elemental\Extensions\ElementalPageExtension
Dynamic\Base\Page\ElementPage:
  extensions:
    - DNADesign\Elemental\Extensions\ElementalPageExtension
Dynamic\CoreTools\Model\GlobalSiteSetting:
  extensions:
    - Dynamic\CoreTools\ORM\GoogleAnalyticsConfig
    - Dynamic\CoreTools\ORM\CompanyConfig
    - Dynamic\SilverStripeGeocoder\AddressDataExtension
    - Dynamic\CoreTools\ORM\TemplateConfig
    - Dynamic\CoreTools\ORM\UtilityNavigationManager
    - Dynamic\CoreTools\ORM\FooterNavigationManager
Dynamic\CoreTools\Model\ContentObject:
  extensions:
    - Dynamic\CoreTools\ORM\Linkable
SilverStripe\ORM\DataList:
  extensions:
    - Dynamic\CoreTools\ORM\CoreToolsDataListDataExtension
SilverStripe\UserForms\Model\EditableFormField:
  extensions:
    - Dynamic\CoreTools\ORM\ContentAuthorPermissionManager
SilverStripe\UserForms\Model\EditableCustomRule:
  extensions:
    - Dynamic\CoreTools\ORM\ContentAuthorPermissionManager
SilverStripe\Blog\Model\BlogPost:
  extensions:
    - Dynamic\CoreTools\ORM\PreviewExtension
    - Dynamic\CoreTools\ORM\CoreToolsBlogPostDataExtension